# Generated by Django 5.0.1 on 2024-06-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_createdat_users_email_users_updatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
    ]
