# Generated by Django 5.0.1 on 2024-06-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='value',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
