# Generated by Django 5.0.1 on 2024-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userphonenumber_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='biographie',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='value',
            field=models.CharField(default='', max_length=15),
        ),
    ]
