# Generated by Django 5.0.1 on 2024-06-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userphonenumber_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='value',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
